//  USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
// User register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
// user favorite
export const ADD_USER_TO_FAVORITE_SUCCESS = 'ADD_USER_TO_FAVORITE_SUCCESS';
export const ADD_USER_TO_FAVORITE_REQUEST = 'ADD_USER_TO_FAVORITE_REQUEST';
export const ADD_USER_TO_FAVORITE_FAIL = 'ADD_USER_TO_FAVORITE_FAIL';
